---
title: "12S Database Summary Statistics"
author: "Marcin Kierczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
setwd('~/Dropbox/WABI/Projects/Snoeijs/12S/')
```

## 12S

```{r}
# grep ">" db_12S.fasta | awk '{print $1,$3,$4,$5}' FS='|' OFS=';' | sed 's/>//g' | sed 's/ ; /;/g' > db_12S_stats.csv
soi <- read.table('species_of_interest.txt', col.names = 'species', sep = '^')
stats <- read.table('db_12S_stats.csv', sep = ';', col.names = c('id', 'family', 'genus', 'species'))

missing <- soi[!(soi$species %in% stats$species),]

counts <- stats %>% 
  group_by(species) %>% 
  summarise(n_seq = n()) %>%
  add_row(species=missing, n_seq = 0) %>%
  arrange(species)

url1 <- paste0('<a href="https://fishbase.se/summary/', str_replace(counts$species,' ', '-'),'.html">', str_replace(counts$species, ' ', '_'), '</a>')
url2 <- paste0('https://fishbase.se/summary/', str_replace(counts$species,' ', '-'),'.html')
img_ls <- list.files('assets/', pattern = ".*(?:jpg|gif)") %>% 
  as_tibble() %>%
  separate(value, into = c('base', 'ext'), sep = "\\.") %>%
  mutate(species = str_replace_all(base, c("_"=" ")))

data <- left_join(x = counts, y = img_ls, by = 'species') %>%
  mutate(img = paste0('assets/', base,'.', ext)) %>%
  mutate(url = url2) %>%
  select(-base, -ext)

img_url <- data$img

data$n_seq <- cell_spec(data$n_seq, 
                        color = ifelse(data$n_seq <= 0, "white", "white"),
                        background = ifelse(data$n_seq <= 0, "red", "slateblue")) 
data %>%
  select(-img) %>%
  kbl(booktabs = T, escape = F) %>%
  kable_paper("striped", full_width = F) %>%
  column_spec(1, image = spec_image(img_url, 200, 100)) %>%
  kable_styling()
```
